### ISSUE TITLE
Permision denied

### ISSUE THREAD

**Issue by ochov1** [selfup/nextjs-docker#9]
I got Permission denied error.

#17 1.813 > Build error occurred
#17 1.816 Error: EACCES: permission denied, open '/app/.next/cache/config.json.3288435009'
#17 1.816     at Object.openSync (node:fs:585:3)
#17 1.816     at Function.writeFileSync [as sync] (/app/node_modules/next/dist/compiled/conf/index.js:15:23035)
#17 1.816     at Conf.set store [as store] (/app/node_modules/next/dist/compiled/conf/index.js:1:109636)

**Comment by selfup** [comment]
Interesting. I will take a look

**Comment by selfup** [comment]
### Attempt to Recreate

I ran a `docker system prune --all && docker-compose up` to make sure I had no cached layers _anywhere_ (**you don't have to do this**) and it built and ran.

I also re-ran the prune command and ran `./scripts/prod.sh` and also no issues.

It sounds like it might be a weird npm cache issue.

---

### Potential Solution

**Try this**: `docker build --no-cache -t nextjs-docker .`

Deleting your container image cache layers for your current project should do the trick.

If you are using docker desktop (I am on linux so no desktop but same docker engine) you should be able to find your image and delete it if you aren't able to clear cache layers of the container itself (not npm cache).

---

### Note

This is aimed at [CI/Building a deployable image] so active development of a project inside the container is not advised.

**Comment by selfup** [comment]
I tried this on 3 different machines with slightly different versions of docker. Not able to reproduce. I will close.

Thanks for reporting!

**Comment by ochov1** [comment]
okay, I have solved the issue in my case, it was my mistake, I have put the USER line before the COPY.
sorry about the inconvenience. have a nice day

**Comment by selfup** [comment]
No worries! Glad you got it fixed 😃
